### ISSUE TITLE
Maintainer Wanted

### ISSUE THREAD

**Issue by benwilson512** [ex-aws/ex_aws_elastic_transcoder#1]
Hey @ericmj, per https://elixirforum.com/t/proposal-exaws-2-0/9269 the ExAws project is splitting out each service into its own project.

You are the original contributor the Elastic Transcoder service to ExAws. If you wish to be its maintainer, please let me know and I will give you commit access to this repository. If you do not want this, let me know and I will look for someone else.

You are already on a lot of projects, so I will completely understand if you don't want this.

Thank you!

**Comment by ericmj** [comment]
We need this at work so you can add me as maintainer. Thank you for ex_aws! ❤️

**Comment by benwilson512** [comment]
Thanks! You have been given write access to this repository.
